.include "./text/globaldestructorchain/globaldestructorchain/code.asm"
.include "./text/ftlucas/ftLucas/code.asm"
.include "./text/ftlucas/ftFighterBuilder/code.asm"
.include "./text/ftlucas/ftStatusGimmickUniqProcessPoolImpl/code.asm"
.include "./text/ftlucas/ftStatusUniqProcessGimmickEaten/code.asm"
.include "./text/ftlucas/ftStatusUniqProcessGimmick/code.asm"
.include "./text/ftlucas/ftStatusUniqProcessGimmickTruck/code.asm"
.include "./text/ftlucas/ftStatusUniqProcessGimmickSpring/code.asm"
.include "./text/ftlucas/ftStatusUniqProcessGimmickLadder/code.asm"
.include "./text/ftlucas/ftStatusUniqProcessGimmickCatapult/code.asm"
.include "./text/ftlucas/ftStatusUniqProcessGimmickDoor/code.asm"
.include "./text/ftlucas/ftStatusUniqProcessGimmickBarrel/code.asm"
.include "./text/ftlucas/ftStatusGimmickUniqProcessPool/code.asm"
.include "./text/ftlucas/ftVirtualNodeMatrixPoolImpl/code.asm"
.include "./text/ftlucas/ftVirtualNodeMatrixPool/code.asm"
.include "./text/ftlucas/ftCancelModuleImpl/code.asm"
.include "./text/ftlucas/soAnimCmdEventObserver/code.asm"
.include "./text/ftlucas/soStatusEventObserver/code.asm"
.include "./text/ftlucas/ftModuleAccesserBuilder/code.asm"
.include "./text/ftlucas/ftAnimCmdModuleSubBuilder/code.asm"
.include "./text/ftlucas/soAnimCmdControlUnitBuilder/code.asm"
.include "./text/ftlucas/soAnimCmdInterpreter/code.asm"
.include "./text/ftlucas/soEventPresenter/code.asm"
.include "./text/ftlucas/soAnimCmdAddressPackArraySeparate/code.asm"
.include "./text/ftlucas/soArraySelectHolder/code.asm"
.include "./text/ftlucas/soModuleAccesserBuilder/code.asm"
.include "./text/ftlucas/soGlowModuleBuilder/code.asm"
.include "./text/ftlucas/soSlowModuleBuilder/code.asm"
.include "./text/ftlucas/soAbnormalModuleBuilder/code.asm"
.include "./text/ftlucas/soJostleModuleBuilder/code.asm"
.include "./text/ftlucas/soColorBlendModuleBuilder/code.asm"
.include "./text/ftlucas/soItemManageModuleBuilder/code.asm"
.include "./text/ftlucas/soShadowModuleBuilder/code.asm"
.include "./text/ftlucas/soSlopeModuleBuilder/code.asm"
.include "./text/ftlucas/soPhysicsModuleBuilder/code.asm"
.include "./text/ftlucas/soAreaModuleBuilder/code.asm"
.include "./text/ftlucas/soComboModuleBuilder/code.asm"
.include "./text/ftlucas/soEffectModuleBuilder/code.asm"
.include "./text/ftlucas/soGenerateArticleManageModuleBuilder/code.asm"
.include "./text/ftlucas/soSelectInstanceHolder/code.asm"
.include "./text/ftlucas/soArticleMediatorImpl/code.asm"
.include "./text/ftlucas/soLineHierarchy/code.asm"
.include "./text/ftlucas/soInstancePool/code.asm"
.include "./text/ftlucas/soInstancePoolSub/code.asm"
.include "./text/ftlucas/wnInstanceHolder/code.asm"
.include "./text/ftlucas/wnLucasPKFlash/code.asm"
.include "./text/ftlucas/wnKineticEnergyGravity/code.asm"
.include "./text/ftlucas/soKineticEnergy/code.asm"
.include "./text/ftlucas/soParamAccesser/code.asm"
.include "./text/ftlucas/soKineticEnergyRotNormal/code.asm"
.include "./text/ftlucas/soReflectModuleBuilder/code.asm"
.include "./text/ftlucas/soGeneralWorkBuilder/code.asm"
.include "./text/ftlucas/soGeneralWorkSimple/code.asm"
.include "./text/ftlucas/soGeneralWorkAbstract/code.asm"
.include "./text/ftlucas/soKineticModuleBuilder/code.asm"
.include "./text/ftlucas/soKineticMediatorNull/code.asm"
.include "./text/ftlucas/soInstanceManagerFullProperty/code.asm"
.include "./text/ftlucas/wnKineticModuleImpl/code.asm"
.include "./text/ftlucas/soKineticModuleImpl/code.asm"
.include "./text/ftlucas/soStatusModuleImpl/code.asm"
.include "./text/ftlucas/soArrayQueueImpl/code.asm"
.include "./text/ftlucas/soTransitionModuleBuilder/code.asm"
.include "./text/ftlucas/soTransitionModuleImpl/code.asm"
.include "./text/ftlucas/soTransitionInfo/code.asm"
.include "./text/ftlucas/soAnimCmdModuleBuilder/code.asm"
.include "./text/ftlucas/soAnimCmdModuleImpl/code.asm"
.include "./text/ftlucas/soWorkManageModuleBuilder/code.asm"
.include "./text/ftlucas/soControllerModuleBuilder/code.asm"
.include "./text/ftlucas/soVisibilityModuleBuilder/code.asm"
.include "./text/ftlucas/soLinkModuleBuilder/code.asm"
.include "./text/ftlucas/soSoundModuleBuilder/code.asm"
.include "./text/ftlucas/soShakeModuleBuilder/code.asm"
.include "./text/ftlucas/soStopModuleBuilder/code.asm"
.include "./text/ftlucas/soCollisionAttackModuleBuilder/code.asm"
.include "./text/ftlucas/soTeamModuleBuilder/code.asm"
.include "./text/ftlucas/soTeam/code.asm"
.include "./text/ftlucas/soSituationModuleBuilder/code.asm"
.include "./text/ftlucas/soGroundModuleBuilder/code.asm"
.include "./text/ftlucas/soPostureModuleBuilder/code.asm"
.include "./text/ftlucas/soModelModuleBuilder/code.asm"
.include "./text/ftlucas/soResourceModuleBuilder/code.asm"
.include "./text/ftlucas/soResourceIdAccesser/code.asm"
.include "./text/ftlucas/soParamCustomizeModuleBuilder/code.asm"
.include "./text/ftlucas/soHeapModuleBuilder/code.asm"
.include "./text/ftlucas/soInsideEventManageModuleBuilder/code.asm"
.include "./text/ftlucas/wnLucasPKFire/code.asm"
.include "./text/ftlucas/wnLucasPKThunder/code.asm"
.include "./text/ftlucas/wnAnimCmdModuleSubBuilder/code.asm"
.include "./text/ftlucas/soMotionModuleBuilder/code.asm"
.include "./text/ftlucas/soArticleMediator/code.asm"
.include "./text/ftlucas/soArticleOperator/code.asm"
.include "./text/ftlucas/soArticleGenerator/code.asm"
.include "./text/ftlucas/wnLucasPKStarStorm/code.asm"
.include "./text/ftlucas/wnLucasHimohebi/code.asm"
.include "./text/ftlucas/soInstanceManagerFullPropertyVector/code.asm"
.include "./text/ftlucas/soKineticModuleGenericImpl/code.asm"
.include "./text/ftlucas/soStatusModuleBuilder/code.asm"
.include "./text/ftlucas/soJagArray/code.asm"
.include "./text/ftlucas/soArrayPool/code.asm"
.include "./text/ftlucas/soCameraModuleBuilder/code.asm"
.include "./text/ftlucas/ftSound3dGeneratorAccesserImpl/code.asm"
.include "./text/ftlucas/soTurnModuleBuilder/code.asm"
.include "./text/ftlucas/soCaptureModuleBuilder/code.asm"
.include "./text/ftlucas/soCatchModuleBuilder/code.asm"
.include "./text/ftlucas/soDamageModuleBuilder/code.asm"
.include "./text/ftlucas/soCollisionCatchModuleBuilder/code.asm"
.include "./text/ftlucas/soCollisionAbsorberModuleBuilder/code.asm"
.include "./text/ftlucas/soCollisionReflectorModuleBuilder/code.asm"
.include "./text/ftlucas/soCollisionShieldModuleBuilder/code.asm"
.include "./text/ftlucas/soCollisionHitModuleBuilder/code.asm"
.include "./text/ftlucas/ftTeamIndirect/code.asm"
.include "./text/ftlucas/ftTeam/code.asm"
.include "./text/ftlucas/soMotionAnimObjCacheModuleBuilder/code.asm"
.include "./text/ftlucas/soNullable/code.asm"
.include "./text/ftlucas/soSingletonHolder/code.asm"
.include "./text/ftlucas/soArrayUtility/code.asm"
.include "./text/ftlucas/Vec3f/code.asm"
.include "./text/ftlucas/Weapon/code.asm"
.include "./text/ftlucas/ftExtendParamAccesser/code.asm"
.include "./text/ftlucas/ftLucasExtendParamAccesser/code.asm"
.include "./text/ftlucas/ftExtendParamAccesserEx/code.asm"
.include "./text/ftlucas/Fighter/code.asm"
.include "./text/ftlucas/soLinkEventObserver/code.asm"
.include "./text/ftlucas/StageObject/code.asm"
.include "./text/ftlucas/soSituationEventObserver/code.asm"
.include "./text/ftlucas/soCollisionAttackEventObserver/code.asm"
.include "./text/ftlucas/soCollisionHitEventObserver/code.asm"
.include "./text/ftlucas/soCollisionShieldEventObserver/code.asm"
.include "./text/ftlucas/soCollisionReflectorEventObserver/code.asm"
.include "./text/ftlucas/soCollisionAbsorberEventObserver/code.asm"
.include "./text/ftlucas/soCollisionSearchEventObserver/code.asm"
.include "./text/ftlucas/soCaptureEventObserver/code.asm"
.include "./text/ftlucas/soItemManageEventObserver/code.asm"
.include "./text/ftlucas/soMotionEventObserver/code.asm"
.include "./text/ftlucas/soDamageEventObserver/code.asm"
.include "./text/ftlucas/ftEntryEventObserver/code.asm"
.include "./text/ftlucas/soTurnEventObserver/code.asm"
.include "./text/ftlucas/soValueAccesser/code.asm"
.include "./text/ftlucas/soKineticMediatorImpl/code.asm"
.include "./text/ftlucas/soArrayFixed/code.asm"
.include "./text/ftlucas/soArticle/code.asm"
.include "./text/ftlucas/ftKineticEnergyMotion/code.asm"
.include "./text/ftlucas/soKineticEnergyHolder/code.asm"
.include "./text/ftlucas/soLineInvertHierarchy/code.asm"
.include "./text/ftlucas/ftKineticEnergyGravity/code.asm"
.include "./text/ftlucas/ftKineticEnergyController/code.asm"
.include "./text/ftlucas/ftKineticEnergyStop/code.asm"
.include "./text/ftlucas/ftKineticEnergyDamage/code.asm"
.include "./text/ftlucas/soKineticEnergyWindNormal/code.asm"
.include "./text/ftlucas/soKineticEnergyGroundMovement/code.asm"
.include "./text/ftlucas/soKineticEnergyJostle/code.asm"
.include "./text/ftlucas/soKineticEnergyNormal/code.asm"
.include "./text/ftlucas/Vec2f/code.asm"
.include "./text/ftlucas/soKineticUpdateEnergyHolderHelper/code.asm"
.include "./text/ftlucas/ftKineticTransactor/code.asm"
.include "./text/ftlucas/soInstancePoolSubNull/code.asm"
.include "./text/ftlucas/ftlucascpp/code.asm"
.include "./text/ftlucas/ftClassInfoImpl/code.asm"
.include "./text/ftlucasstatusuniqprocessattacks4/ftLucasStatusUniqProcessAttackS4/code.asm"
.include "./text/ftlucasstatusuniqprocessattacks4/soStatusUniqProcess/code.asm"
.include "./text/ftlucasstatusuniqprocessattacks4/ftlucasstatusuniqprocessattacks4cpp/code.asm"
.include "./text/ftlucasstatusuniqprocessairlasso/ftLucasStatusUniqProcessAirLasso/code.asm"
.include "./text/ftlucasstatusuniqprocessairlasso/ftlucasstatusuniqprocessairlassocpp/code.asm"
.include "./text/ftlucasstatusuniqprocessspecials/ftLucasStatusUniqProcessSpecialS/code.asm"
.include "./text/ftlucasstatusuniqprocessspecials/ftlucasstatusuniqprocessspecialscpp/code.asm"
.include "./text/ftlucasstatusuniqprocessspecialhi/ftLucasStatusUniqProcessSpecialHi/code.asm"
.include "./text/ftlucasstatusuniqprocessspecialhi/ftlucasstatusuniqprocessspecialhicpp/code.asm"
.include "./text/ftlucasstatusuniqprocessspecialhiattack/ftLucasStatusUniqProcessSpecialHiAttack/code.asm"
.include "./text/ftlucasstatusuniqprocessspecialhiattack/Vec2f/code.asm"
.include "./text/ftlucasstatusuniqprocessspecialhiattack/ftlucasstatusuniqprocessspecialhiattackcpp/code.asm"
.include "./text/ftlucasstatusuniqprocessspecialhiattackend/ftLucasStatusUniqProcessSpecialHiAttackEnd/code.asm"
.include "./text/ftlucasstatusuniqprocessspecialhiattackend/ftlucasstatusuniqprocessspecialhiattackendcpp/code.asm"
.include "./text/ftlucasstatusuniqprocessspecialhireflect/ftLucasStatusUniqProcessSpecialHiReflect/code.asm"
.include "./text/ftlucasstatusuniqprocessspecialhireflect/ftlucasstatusuniqprocessspecialhireflectcpp/code.asm"
.include "./text/ftlucasstatusuniqprocessspeciallw/ftLucasStatusUniqProcessSpecialLw/code.asm"
.include "./text/ftlucasstatusuniqprocessspeciallw/ftlucasstatusuniqprocessspeciallwcpp/code.asm"
.include "./text/ftlucasstatusuniqprocessspeciallwhold/ftLucasStatusUniqProcessSpecialLwHold/code.asm"
.include "./text/ftlucasstatusuniqprocessspeciallwhold/Vec3f/code.asm"
.include "./text/ftlucasstatusuniqprocessspeciallwhold/ftlucasstatusuniqprocessspeciallwholdcpp/code.asm"
.include "./text/wnlucaspkfire/wnLucasPKFire/code.asm"
.include "./text/wnlucaspkfire/wnWeaponBuilder/code.asm"
.include "./text/wnlucaspkfire/wnModuleAccesserBuilder/code.asm"
.include "./text/wnlucaspkfire/wnAnimCmdModuleSubBuilder/code.asm"
.include "./text/wnlucaspkfire/soAnimCmdControlUnitBuilder/code.asm"
.include "./text/wnlucaspkfire/soModuleAccesserBuilder/code.asm"
.include "./text/wnlucaspkfire/soStatusModuleBuilder/code.asm"
.include "./text/wnlucaspkfire/soArraySelectHolder/code.asm"
.include "./text/wnlucaspkfire/soDamageModuleBuilder/code.asm"
.include "./text/wnlucaspkfire/soCollisionHitModuleBuilder/code.asm"
.include "./text/wnlucaspkfire/soCollisionAttackModuleBuilder/code.asm"
.include "./text/wnlucaspkfire/soTeamImpl/code.asm"
.include "./text/wnlucaspkfire/soMotionModuleBuilder/code.asm"
.include "./text/wnlucaspkfire/soResourceIdAccesserImpl/code.asm"
.include "./text/wnlucaspkfire/soParamCustomizeModuleImpl/code.asm"
.include "./text/wnlucaspkfire/soParamCustomizeModule/code.asm"
.include "./text/wnlucaspkfire/wnLucasPKFireParamAccesser/code.asm"
.include "./text/wnlucaspkfire/soKineticEnergy/code.asm"
.include "./text/wnlucaspkfire/soCollisionAttackAbsolute/code.asm"
.include "./text/wnlucaspkfire/soDamageTransactorNull/code.asm"
.include "./text/wnlucaspkfire/soDamageEffector/code.asm"
.include "./text/wnlucaspkfire/soDamageEffectorNull/code.asm"
.include "./text/wnlucaspkfire/Weapon/code.asm"
.include "./text/wnlucaspkfire/StageObject/code.asm"
.include "./text/wnlucaspkfire/Input/code.asm"
.include "./text/wnlucaspkfire/IpNull/code.asm"
.include "./text/wnlucaspkfire/soCollisionHitEventObserver/code.asm"
.include "./text/wnlucaspkfire/soArticle/code.asm"
.include "./text/wnlucaspkfire/soArticleMediatorNull/code.asm"
.include "./text/wnlucaspkfire/soKineticMediatorNull/code.asm"
.include "./text/wnlucaspkfire/soDamageTransactor/code.asm"
.include "./text/wnlucaspkfire/wnExtendParamAccesser/code.asm"
.include "./text/wnlucaspkfirestatusuniqprocessshoot/wnLucasPKFireStatusUniqProcessShoot/code.asm"
.include "./text/wnlucaspkfirestatusuniqprocessshoot/wnlucaspkfirestatusuniqprocessshootcpp/code.asm"
.include "./text/wnlucaspkfirestatusuniqprocesspillar/wnLucasPKFireStatusUniqProcessPillar/code.asm"
.include "./text/wnlucaspkfirestatusuniqprocesspillar/wnlucaspkfirestatusuniqprocesspillarcpp/code.asm"
.include "./text/wnlucaspkthunder/wnLucasPKThunder/code.asm"
.include "./text/wnlucaspkthunder/wnWeaponBuilder/code.asm"
.include "./text/wnlucaspkthunder/wnModuleAccesserBuilder/code.asm"
.include "./text/wnlucaspkthunder/soModuleAccesserBuilder/code.asm"
.include "./text/wnlucaspkthunder/soGenerateArticleManageModuleBuilder/code.asm"
.include "./text/wnlucaspkthunder/soSelectInstanceHolder/code.asm"
.include "./text/wnlucaspkthunder/soArticleMediatorImpl/code.asm"
.include "./text/wnlucaspkthunder/soLineHierarchy/code.asm"
.include "./text/wnlucaspkthunder/soInstancePool/code.asm"
.include "./text/wnlucaspkthunder/soInstancePoolSub/code.asm"
.include "./text/wnlucaspkthunder/wnLucasPKThunderChild/code.asm"
.include "./text/wnlucaspkthunder/soStatusModuleBuilder/code.asm"
.include "./text/wnlucaspkthunder/soGeneralWorkBuilder/code.asm"
.include "./text/wnlucaspkthunder/wnLucasPKThunderParamAccesser/code.asm"
.include "./text/wnlucaspkthunder/wnInstanceHolder/code.asm"
.include "./text/wnlucaspkthunder/Vec2f/code.asm"
.include "./text/wnlucaspkthunder/wnExtendParamAccesser/code.asm"
.include "./text/wnlucaspkthunderstatusuniqprocessmove/wnLucasPKThunderStatusUniqProcessMove/code.asm"
.include "./text/wnlucaspkthunderstatusuniqprocessmove/wnlucaspkthunderstatusuniqprocessmovecpp/code.asm"
.include "./text/wnlucaspkthunderchild/wnLucasPKThunderChild/code.asm"
.include "./text/wnlucaspkthunderchild/wnWeaponBuilder/code.asm"
.include "./text/wnlucaspkthunderchild/wnModuleAccesserBuilder/code.asm"
.include "./text/wnlucaspkthunderchild/soModuleAccesserBuilder/code.asm"
.include "./text/wnlucaspkthunderchild/soStatusModuleBuilder/code.asm"
.include "./text/wnlucaspkthunderchild/soGeneralWorkBuilder/code.asm"
.include "./text/wnlucaspkthunderchild/soLinkModuleBuilder/code.asm"
.include "./text/wnlucaspkthunderchild/wnLucasPKThunderChildParamAccesser/code.asm"
.include "./text/wnlucaspkthunderchild/Vec3f/code.asm"
.include "./text/wnlucaspkthunderchild/wnExtendParamAccesser/code.asm"
.include "./text/wnlucaspkthunderchildstatusuniqprocessmove/wnLucasPKThunderChildStatusUniqProcessMove/code.asm"
.include "./text/wnlucaspkthunderchildstatusuniqprocessmove/wnlucaspkthunderchildstatusuniqprocessmovecpp/code.asm"
.include "./text/wnlucaspkstarstorm/wnLucasPKStarStorm/code.asm"
.include "./text/wnlucaspkstarstorm/wnWeaponBuilder/code.asm"
.include "./text/wnlucaspkstarstorm/wnModuleAccesserBuilder/code.asm"
.include "./text/wnlucaspkstarstorm/soModuleAccesserBuilder/code.asm"
.include "./text/wnlucaspkstarstorm/soKineticModuleBuilder/code.asm"
.include "./text/wnlucaspkstarstorm/soInstanceManagerFullPropertyVector/code.asm"
.include "./text/wnlucaspkstarstorm/soStatusModuleBuilder/code.asm"
.include "./text/wnlucaspkstarstorm/soModelModuleBuilder/code.asm"
.include "./text/wnlucaspkstarstorm/soInsideEventManageModuleBuilder/code.asm"
.include "./text/wnlucaspkstarstorm/wnLucasPKStarStormParamAccesser/code.asm"
.include "./text/wnlucaspkstarstorm/Vec2f/code.asm"
.include "./text/wnlucaspkstarstorm/wnExtendParamAccesser/code.asm"
.include "./text/wnlucashimohebi/wnLucasHimohebi/code.asm"
.include "./text/wnlucashimohebi/wnWeaponBuilder/code.asm"
.include "./text/wnlucashimohebi/wnModuleAccesserBuilder/code.asm"
.include "./text/wnlucashimohebi/wnAnimCmdModuleSubBuilder/code.asm"
.include "./text/wnlucashimohebi/soAnimCmdControlUnitBuilder/code.asm"
.include "./text/wnlucashimohebi/soModuleAccesserBuilder/code.asm"
.include "./text/wnlucashimohebi/soColorBlendModuleBuilder/code.asm"
.include "./text/wnlucashimohebi/soPhysicsModuleBuilder/code.asm"
.include "./text/wnlucashimohebi/soStatusModuleBuilder/code.asm"
.include "./text/wnlucashimohebi/soArraySelectHolder/code.asm"
.include "./text/wnlucashimohebi/soGeneralWorkBuilder/code.asm"
.include "./text/wnlucashimohebi/soMotionModuleBuilder/code.asm"
.include "./text/wnlucashimohebi/soInsideEventManageModuleBuilder/code.asm"
.include "./text/wnlucashimohebi/wnLucasHimohebiParamAccesser/code.asm"
.include "./text/wnlucashimohebi/wnExtendParamAccesser/code.asm"
.include "./text/wnlucashimohebistatusuniqprocessexhaust/wnLucasHimohebiStatusUniqProcessExhaust/code.asm"
    /* 00020E94: */    lis r4,0x0                               [R_PPC_ADDR16_HA(114, 5, "wnLucasHimohebiStatusUniqProcessExhaustClassObject")]
    /* 00020E98: */    addi r4,r4,0x0                           [R_PPC_ADDR16_LO(114, 5, "wnLucasHimohebiStatusUniqProcessExhaustClassObject")]

.include "./text/wnlucashimohebistatusuniqprocessexhaust/wnlucashimohebistatusuniqprocessexhaustcpp/code.asm"
__entry:
    /* 00020EA4: */    stwu r1,-0x10(r1)
    /* 00020EA8: */    mflr r0
    /* 00020EAC: */    stw r0,0x14(r1)
    /* 00020EB0: */    stw r31,0xC(r1)
    /* 00020EB4: */    lis r31,0x0                              [R_PPC_ADDR16_HA(114, 2, "loc_0")]
    /* 00020EB8: */    addi r31,r31,0x0                         [R_PPC_ADDR16_LO(114, 2, "loc_0")]
    /* 00020EBC: */    b loc_20ECC
loc_20EC0:
    /* 00020EC0: */    mtctr r12
    /* 00020EC4: */    bctrl
    /* 00020EC8: */    addi r31,r31,0x4
loc_20ECC:
    /* 00020ECC: */    lwz r12,0x0(r31)
    /* 00020ED0: */    cmpwi r12,0x0
    /* 00020ED4: */    bne+ loc_20EC0
    /* 00020ED8: */    lwz r0,0x14(r1)
    /* 00020EDC: */    lwz r31,0xC(r1)
    /* 00020EE0: */    mtlr r0
    /* 00020EE4: */    addi r1,r1,0x10
    /* 00020EE8: */    blr
__exit:
    /* 00020EEC: */    stwu r1,-0x10(r1)
    /* 00020EF0: */    mflr r0
    /* 00020EF4: */    stw r0,0x14(r1)
    /* 00020EF8: */    stw r31,0xC(r1)
    /* 00020EFC: */    lis r31,0x0                              [R_PPC_ADDR16_HA(114, 3, "loc_0")]
    /* 00020F00: */    addi r31,r31,0x0                         [R_PPC_ADDR16_LO(114, 3, "loc_0")]
    /* 00020F04: */    b loc_20F14
loc_20F08:
    /* 00020F08: */    mtctr r12
    /* 00020F0C: */    bctrl
    /* 00020F10: */    addi r31,r31,0x4
loc_20F14:
    /* 00020F14: */    lwz r12,0x0(r31)
    /* 00020F18: */    cmpwi r12,0x0
    /* 00020F1C: */    bne+ loc_20F08
    /* 00020F20: */    lwz r0,0x14(r1)
    /* 00020F24: */    lwz r31,0xC(r1)
    /* 00020F28: */    mtlr r0
    /* 00020F2C: */    addi r1,r1,0x10
    /* 00020F30: */    blr
__unresolved:
    /* 00020F34: */    lis r3,0x0                               [R_PPC_ADDR16_HA(114, 5, "loc_B538")]
    /* 00020F38: */    addi r3,r3,0x0                           [R_PPC_ADDR16_LO(114, 5, "loc_B538")]
